
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.ObjectOutputStream;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mikhail
 */
public class GUI_Main extends javax.swing.JFrame {
    
    //attributes
    String server;
    String username;
    int port;
	String messageType;
	User activeUser;
	ChatAppClient client;
    /**
     * Creates new form ChatAppGUI
     */
    public GUI_Main(String username, String _server, int _port) {
        this.username = username;
        this.server = _server;
        this.port = _port;
		messageType = "broadcast";
		activeUser = new User(username, server);
		client = new ChatAppClient(server, port, username, this);
        initComponents();
		lbl_Heading.setText("Welcome " + username);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grp_messageType = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txa_ChatArea = new javax.swing.JTextArea();
        lbl_ChatArea = new javax.swing.JLabel();
        lbl_Heading = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txa_newMessage = new javax.swing.JTextArea();
        lbl_typeHere = new javax.swing.JLabel();
        rb_broadcast = new javax.swing.JRadioButton();
        rb_private = new javax.swing.JRadioButton();
        rb_file = new javax.swing.JRadioButton();
        btn_attach = new javax.swing.JButton();
        btn_send = new javax.swing.JButton();
        txf_sendTo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        txa_ChatArea.setEditable(false);
        txa_ChatArea.setColumns(20);
        txa_ChatArea.setRows(5);
        jScrollPane1.setViewportView(txa_ChatArea);

        lbl_ChatArea.setText("Chat Area");

        lbl_Heading.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        lbl_Heading.setText("ChatApp");

        txa_newMessage.setColumns(20);
        txa_newMessage.setRows(5);
        jScrollPane2.setViewportView(txa_newMessage);

        lbl_typeHere.setText("Type Message Here:");

        grp_messageType.add(rb_broadcast);
        rb_broadcast.setText("broadcast");
        rb_broadcast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_broadcastActionPerformed(evt);
            }
        });

        grp_messageType.add(rb_private);
        rb_private.setText("private");
        rb_private.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_privateActionPerformed(evt);
            }
        });

        grp_messageType.add(rb_file);
        rb_file.setText("file");
        rb_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_fileActionPerformed(evt);
            }
        });

        btn_attach.setText("Attach File");

        btn_send.setText("Send");
        btn_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendActionPerformed(evt);
            }
        });

        txf_sendTo.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_Heading)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_typeHere)
                    .addComponent(rb_broadcast)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rb_private)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txf_sendTo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rb_file)
                    .addComponent(btn_attach)
                    .addComponent(btn_send))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_ChatArea)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_ChatArea)
                            .addComponent(lbl_typeHere))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_Heading)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rb_broadcast)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb_private)
                            .addComponent(txf_sendTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_file)
                        .addGap(18, 18, 18)
                        .addComponent(btn_attach)
                        .addGap(18, 18, 18)
                        .addComponent(btn_send))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb_broadcastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_broadcastActionPerformed
        // TODO add your handling code here:
		messageType = "broadcast";
		btn_attach.setEnabled(false);
		txf_sendTo.setEnabled(false);
    }//GEN-LAST:event_rb_broadcastActionPerformed

    private void rb_privateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_privateActionPerformed
        // TODO add your handling code here:
		messageType = "private";
		btn_attach.setEnabled(false);
		txf_sendTo.setEnabled(true);
    }//GEN-LAST:event_rb_privateActionPerformed

    private void rb_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_fileActionPerformed
        // TODO add your handling code here:
		messageType = "file";
		btn_attach.setEnabled(true);
		txf_sendTo.setEnabled(false);
    }//GEN-LAST:event_rb_fileActionPerformed

    private void btn_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendActionPerformed

		boolean empty = txa_newMessage.getText().equals("");
		if((!messageType.equals("file") && empty))//error prevention
		{
			JOptionPane.showMessageDialog(this, "No message was entered");
		}
		else if(messageType.equals("broadcast"))
		{
			String userInput = txa_newMessage.getText();
			send("broadcast", userInput, "all");
		}
		else if(messageType.equals("private"))
		{
			String sendTo = txf_sendTo.getText();
			String userInput = txa_newMessage.getText();
			send("private", userInput, sendTo);
		}
		else//send file
		{
			String filepath = JOptionPane.showInputDialog(this, "Enter filepath for file");
			//TODO:call file attach methods
		}
		txa_newMessage.setText("");
    }//GEN-LAST:event_btn_sendActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        client.shutdown();
    }//GEN-LAST:event_formWindowClosing

	//given a message, print to textArea
	public void recieve(String message)
	{
		txa_ChatArea.append(message);
	}
	
	//given an input message, send to client class
	public void send(String type, String message, String sendTo)
	{
		client.send(type, message, sendTo);
	}
/*
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Main().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_attach;
    private javax.swing.JButton btn_send;
    private javax.swing.ButtonGroup grp_messageType;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_ChatArea;
    private javax.swing.JLabel lbl_Heading;
    private javax.swing.JLabel lbl_typeHere;
    private javax.swing.JRadioButton rb_broadcast;
    private javax.swing.JRadioButton rb_file;
    private javax.swing.JRadioButton rb_private;
    private javax.swing.JTextArea txa_ChatArea;
    private javax.swing.JTextArea txa_newMessage;
    private javax.swing.JTextField txf_sendTo;
    // End of variables declaration//GEN-END:variables
}
