
import java.awt.TextField;
import java.io.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mikhail
 */
public class GUI_Welcome extends javax.swing.JFrame {

    //Attributes
    private boolean isSimple;
    private static int PORT_NUMBER = 6000;
    /**
     * Creates new form GUI_Login
     */
    public GUI_Welcome() {
        initComponents();
        isSimple = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grp_login = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        txf_username = new javax.swing.JTextField();
        btn_continue = new javax.swing.JButton();
        rb_simple = new javax.swing.JRadioButton();
        rb_advanced = new javax.swing.JRadioButton();
        lbl_server = new javax.swing.JLabel();
        lbl_port = new javax.swing.JLabel();
        txf_port = new javax.swing.JTextField();
        txf_server = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setText("Welcome to ChatApp");

        lbl_username.setText("Username:");

        btn_continue.setText("Continue");
        btn_continue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_continueActionPerformed(evt);
            }
        });

        grp_login.add(rb_simple);
        rb_simple.setSelected(true);
        rb_simple.setText("Simple");
        rb_simple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_simpleActionPerformed(evt);
            }
        });

        grp_login.add(rb_advanced);
        rb_advanced.setText("Advanced");
        rb_advanced.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_advancedActionPerformed(evt);
            }
        });

        lbl_server.setText("Server IP:");

        lbl_port.setText("Port:");

        txf_port.setEditable(false);
        txf_port.setEnabled(false);

        txf_server.setEditable(false);
        txf_server.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_port)
                        .addGap(56, 56, 56)
                        .addComponent(txf_port, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_username)
                        .addGap(18, 18, 18)
                        .addComponent(txf_username, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_simple)
                            .addComponent(lbl_server))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(txf_server))
                            .addComponent(rb_advanced))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(btn_continue)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_username)
                    .addComponent(txf_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_simple)
                    .addComponent(rb_advanced))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_server)
                    .addComponent(txf_server, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_continue)
                    .addComponent(lbl_port)
                    .addComponent(txf_port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb_simpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_simpleActionPerformed
        // TODO add your handling code here:
        txf_server.setEditable(false);
        txf_server.setEnabled(false);
        txf_port.setEditable(false);
        txf_port.setEnabled(false);
        isSimple = true;
    }//GEN-LAST:event_rb_simpleActionPerformed

    private void rb_advancedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_advancedActionPerformed
        // TODO add your handling code here:
        txf_server.setEditable(true);
        txf_port.setEditable(true);
        txf_server.setEnabled(true);
        txf_port.setEnabled(true);
        isSimple = false;
    }//GEN-LAST:event_rb_advancedActionPerformed

    private void btn_continueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_continueActionPerformed
        // TODO add your handling code here:
        String username = txf_username.getText();
        String server = "";
        int port = PORT_NUMBER;
        if(!isSimple)
        {
            server = txf_server.getText();
            port = Integer.parseInt(txf_port.getText());
	}
        else
        {
            server = getHostName(port);
            
        }
        if(AuthManager.exists(username))//if username exists, make them login
        {
            this.setVisible(false);
	    new GUI_Login(username,server, port, false).setVisible(true);
        }
        else
        {
	    this.setVisible(false);
	    new GUI_Login(username,server, port, true).setVisible(true);
        }
        
    }//GEN-LAST:event_btn_continueActionPerformed

    
    //Returns hostname
    public static String getHostName(int portNumber)
    {
	    String hostname = null;
	    System.out.println("Fetching hostname and using Port Number " + portNumber);
	    try{

		    Process p = Runtime.getRuntime().exec("hostname");//run the hostname command
		    BufferedReader input = new BufferedReader(new InputStreamReader(p.getInputStream()));
		    String line = null;

		    while((line = input.readLine()) != null)
		    {
			    hostname = line;
		    }//end while
		    return hostname;
	    }//end try
	    catch (IOException e)
	    {
		    System.out.println(e);
		    return e.toString();
	    }
    }//end getHostName
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //get user info

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_continue;
    private javax.swing.ButtonGroup grp_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_port;
    private javax.swing.JLabel lbl_server;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JRadioButton rb_advanced;
    private javax.swing.JRadioButton rb_simple;
    private javax.swing.JTextField txf_port;
    private javax.swing.JTextField txf_server;
    private javax.swing.JTextField txf_username;
    // End of variables declaration//GEN-END:variables
}
